### ISSUE TITLE
Missing /admin from paths

### ISSUE THREAD

**Issue by drjekyll** [pqrs/l5b-crud#5]
In a the stubs where you generate links to view items using <a href="/DummyRoute/..." the href should be "/admin/DummyRoute/...".  I think it's only in the make-views-index and make-views-deleted.  I was planning to make a pull request for these - but if you are going to be making changes you might get there faster than I will.

**Comment by pqrs** [comment]
It's corrected now, thanks for pointing.

I saw you also corrected the labels for the FlashSuccess messages in the Controller. It is changed too.

I'll commit these changes in a minute.
