### ISSUE TITLE
Request: seperate lang files

### ISSUE THREAD

**Issue by rabol** [pqrs/l5b-crud#7]
Hi 

First of - Thanks for the package

May I suggest a new language file is generated for each CRUD.
If there is separate files then one does not need to update 'core' files

**Comment by pqrs** [comment]
Hi @rabol and thanks for your comment. This is a really good idea, I'll try to implement it soon. Will keep you updated.

**Comment by pqrs** [comment]
Issue closed as issue has been added in version 1.4.
